name = "couchdb"
main = "src/index.js"
compatibility_date = "2023-12-01"

[vars]
# Environment variables for your Worker
COUCHDB_URL = "https://couchdb.brisflix.workers.dev:5984" # Replace with your actual CouchDB URL

# Uncomment if you need KV storage
# [[kv_namespaces]]
# binding = "COUCHDB_KV"
# id = "your-kv-namespace-id"

# Uncomment if you need Durable Objects
# [[durable_objects.bindings]]
# name = "COUCHDB_DO"
# class_name = "CouchDBDurableObject"

# Uncomment if you need R2 storage
# [[r2_buckets]]
# binding = "COUCHDB_BUCKET"
# bucket_name = "your-bucket-name"